//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Book
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Publication { get; set; }
        public long IdAuthor { get; set; }
    
        public virtual T_Author T_Author { get; set; }
    }
}
